import type { Metadata } from "next";
import "./globals.css";
import MenuProvider from "@/contexts/openMenuContext";

import Footer from "@/components/footer";


export const metadata: Metadata = {
  title: "Workly",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <MenuProvider>
      <html lang="pt-br">
        <head>

        </head>
        <body>
          {children}
          <Footer/>
        </body>
      </html>
    </MenuProvider>
  );
}
